
[buildpack]
id = "org.cloudfoundry.pipenv"
name = "Pipenv Buildpack"
version = "0.0.4"

[metadata]
include_files = ["bin/build","bin/detect","buildpack.toml"]
pre_package = "./scripts/build.sh"

[[metadata.dependencies]]
id = "pipenv"
name = "Pipenv"
sha256 = "9e84619a4d471ad8d67ff87431c22bce33175ef070742a34727bd7a48c0d051d"
source = "https://files.pythonhosted.org/packages/fd/e9/01822318551caa0d62a181ba3b10f0f3757bb1e270da97165bd52db92776/pipenv-2018.11.26.tar.gz"
source_sha256 = "a673e606e8452185e9817a987572b55360f4d28b50831ef3b42ac3cab3fee846"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/pipenv/pipenv-v2018.11.26-cflinuxfs3-9e84619a.tgz"
version = "2018.11.26"

[[stacks]]
id = "org.cloudfoundry.stacks.cflinuxfs3"
